### ISSUE TITLE
Smart City Strategic Plan Content

### ISSUE THREAD

**Issue by mgottholsen** [louisvillemetro-innovation/OPI2-Projects#15]
_From @mgottholsen on February 15, 2018 13:43_

Need to build out content for https://projects.lsvll.io/projects/smart-city/

_Copied from original issue: LouisvilleMetro/OPI2-Projects#8_

**Comment by mgottholsen** [comment]
Will add Ed once he gets Github access

**Comment by edblayney** [comment]
Updated content
