### ISSUE TITLE
Data Governance Content

### ISSUE THREAD

**Issue by mgottholsen** [louisvillemetro-innovation/OPI2-Projects#20]
Need to build out content for https://projects.lsvll.io/projects/data-governance/

If you all want to add a Markdown file of your content here, I can put it in the site, or you're welcome to update the Markdown file in the site itself, located here: https://github.com/LouisvilleMetro/OPI2-Projects/tree/data-governance-content/_projects/data-governance

**Comment by schnuerle** [comment]
Data governance content is updated with a good first pass.  More work to be done but good for launch.
